### ISSUE TITLE
Cant play a game

### ISSUE THREAD

**Issue by CharCharSauce** [TTNO1/Bedwars-Plus#2]
I tried to use /startgame and it said an internal command occurred, see more info in the console but there is no info in console.

**Comment by CharCharSauce** [comment]
[01:08:00] [Server thread/INFO]: CharFarGaSquar issued server command: /bw startgame 4Teams                                                                                                                                                                                    [01:08:00] [Server thread/ERROR]: null                                                                                                                                                                                                                                         org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin Bedwars-Plus v1.2                                                                                                                                                                            at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                             at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                     at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                           at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                    at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                  at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                   at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                 at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                                   at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                 at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                         at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                 at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                  at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                         at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                  at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                   at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                            at java.lang.Thread.run(Thread.java:834) [?:?]                                                                                                                                                                                                                         Caused by: java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4                                                                                                                                                                                                     at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]                                                                                                                                                                                                   at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]                                                                                                                                                                                         at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]                                                                                                                                                                                                   at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]                                                                                                                                                                                                                       at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]                                                                                                                                                                                                                          at me.ttno1.bedwars.Game.startGame(Game.java:617) ~[?:?]                                                                                                                                                                                                                       at me.ttno1.bedwars.CommandBedwars.onCommand(CommandBedwars.java:259) ~[?:?]                                                                                                                                                                                                   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]                                                                                                                                                             ... 18 more

**Comment by TTNO1** [comment]
I am currently not able to check my computer but it is most likely because you forgot to set something while you were setting up your game. In the future the setup process will be much better, I am sorry for the inconvenience.

**Comment by xEPICAIDANx** [comment]
same for me
I spent 2 hours setting everything up and it wont start

**Comment by Ari7621** [comment]
i still cant start it up even though i setted it up properly
