### ISSUE TITLE
When running /bw startgame, the console goes crazy.

### ISSUE THREAD

**Issue by SavageMusicYT** [TTNO1/Bedwars-Plus#9]
I have set everything up correctly and the game is in a separate world. Why is my console full of errors?

(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:15] [Server thread/WARN]: [Bedwars-Plus] Task #395 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:15] [Server thread/WARN]: [Bedwars-Plus] Task #402 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:15] [Async Chat Thread - #15/INFO]: [KitPVP]KitPVP [Admin] Olly_Green: oh rip
> [16:57:16] [Server thread/WARN]: [Bedwars-Plus] Task #395 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:16] [Server thread/WARN]: [Bedwars-Plus] Task #402 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:17] [Server thread/WARN]: [Bedwars-Plus] Task #395 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:17] [Server thread/WARN]: [Bedwars-Plus] Task #402 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
> [16:57:18] [Server thread/WARN]: [Bedwars-Plus] Task #395 for Bedwars-Plus v1.2 generated an exception
java.lang.NullPointerException: null
at me.ttno1.bedwars.Generator$3.run(Generator.java:117) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:3016-Spigot-73fb609-ea050e6]

**Comment by SavageMusicYT** [comment]
im in 1.16 btw

**Comment by NotMifa** [comment]
Same here

im on 1.18.1
